//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GecmisDetaylar
    {
        public int GecmisSiparisId { get; set; }
        public int GecmisUrunId { get; set; }
        public int GecmisDetayId { get; set; }
    
        public virtual GecmisSiparisler GecmisSiparisler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
