//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GecmisSiparisler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GecmisSiparisler()
        {
            this.GecmisDetaylar = new HashSet<GecmisDetaylar>();
        }
    
        public int GecmisSiparisId { get; set; }
        public int GecmisMusteriId { get; set; }
        public string VerilmeZamani { get; set; }
        public string TeslimZamani { get; set; }
        public string VerilmeTarihi { get; set; }
        public string TeslimTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GecmisDetaylar> GecmisDetaylar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
