//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafe.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasaBilgileri
    {
        public int BilgiId { get; set; }
        public string MasaId { get; set; }
        public int MusteriId { get; set; }
        public string AcilmaTarihi { get; set; }
        public string AcilmaZamani { get; set; }
    
        public virtual Masalar Masalar { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
